const googleTags = {
	proper: [
		{
			label: ' PROPER_UNKNOWN ',
			description:
				' Proper is not applicable in the analyzed language or is not predicted.  ',
		},
		{ label: ' PROPER ', description: ' Proper nome ' },
		{ label: ' NOT_ROPER ', description: 'Not proper' },
	],
	number: [
		{
			label: 'NUMBER_UNKNOWN',
			description:
				'Number is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'SINGULAR', description: 'Singular' },
		{ label: 'PLURAL', description: 'Plural' },
		{ label: 'DUAL', description: 'Dual' },
	],
	tag: [
		{ label: 'UNKNOWN', description: 'Unknown' },
		{ label: 'ADJ', description: 'Adjective' },
		{ label: 'ADP', description: 'Adposition (preposition or postposition)' },
		{ label: 'ADV', description: 'Adverb' },
		{ label: 'CONJ', description: 'Conjunction' },
		{ label: 'DET', description: 'Determiner' },
		{ label: 'NOUN', description: 'Noun (common and proper)' },
		{ label: 'NUM', description: 'Cardinal number' },
		{ label: 'PRON', description: 'Pronoun' },
		{ label: 'PRT', description: 'Particle or other function word' },
		{ label: 'PUNCT', description: 'Punctuation' },
		{ label: 'VERB', description: 'Verb' },
		{ label: 'X', description: 'Other: foreign words, typos, abbreviations' },
		{ label: 'AFFIX', description: 'Affix' },
	],
	aspect: [
		{
			label: 'ASPECT_UNKNOWN',
			description:
				'Aspect is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'PERFECTIVE', description: 'Perfective' },
		{ label: 'IMPERFECTIVE', description: 'Imperfective' },
		{ label: 'PROGRESSIVE', description: 'Progressive' },
	],
	case: [
		{
			label: 'CASE_UNKNOWN',
			description:
				'Case is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'ACCUSATIVE', description: 'Accusative' },
		{ label: 'ADVERBIAL', description: 'Adverbial' },
		{ label: 'COMPLEMENTIVE', description: 'Complementive' },
		{ label: 'DATIVE', description: 'Dative' },
		{ label: 'GENITIVE', description: 'Genitive' },
		{ label: 'INSTRUMENTAL', description: 'Instrumental' },
		{ label: 'LOCATIVE', description: 'Locative' },
		{ label: 'NOMINATIVE', description: 'Nominative' },
		{ label: 'OBLIQUE', description: 'Oblique' },
		{ label: 'PARTITIVE', description: 'Partitive' },
		{ label: 'PREPOSITIONAL', description: 'Prepositional' },
		{ label: 'REFLEXIVE_CASE', description: 'Reflexive' },
		{ label: 'RELATIVE_CASE', description: 'Relative' },
		{ label: 'VOCATIVE', description: 'Vocative' },
	],
	form: [
		{
			label: 'FORM_UNKNOWN',
			description:
				'Form is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'ADNOMIAL', description: 'Adnomial' },
		{ label: 'AUXILIARY', description: 'Auxiliary' },
		{ label: 'COMPLEMENTIZER', description: 'Complementizer' },
		{ label: 'FINAL_ENDING', description: 'Final ending' },
		{ label: 'GERUND', description: 'Gerund' },
		{ label: 'REALIS', description: 'Realis' },
		{ label: 'IRREALIS', description: 'Irrealis' },
		{ label: 'SHORT', description: 'Short form' },
		{ label: 'LONG', description: 'Long form' },
		{ label: 'ORDER', description: 'Order form' },
		{ label: 'SPECIFIC', description: 'Specific form' },
	],
	gender: [
		{
			label: 'GENDER_UNKNOWN',
			description:
				'Gender is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'FEMININE', description: 'Feminine' },
		{ label: 'MASCULINE', description: 'Masculine' },
		{ label: 'NEUTER', description: 'Neuter' },
	],
	mood: [
		{
			label: 'MOOD_UNKNOWN',
			description:
				'Mood is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'CONDITIONAL_MOOD', description: 'Conditional' },
		{ label: 'IMPERATIVE', description: 'Imperative' },
		{ label: 'INDICATIVE', description: 'Indicative' },
		{ label: 'INTERROGATIVE', description: 'Interrogative' },
		{ label: 'JUSSIVE', description: 'Jussive' },
		{ label: 'SUBJUNCTIVE', description: 'Subjunctive' },
	],
	person: [
		{
			label: 'PERSON_UNKNOWN',
			description:
				'Person is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'FIRST', description: 'First' },
		{ label: 'SECOND', description: 'Second' },
		{ label: 'THIRD', description: 'Third' },
		{ label: 'REFLEXIVE_PERSON', description: 'Reflexive' },
	],
	reciprocity: [
		{
			label: 'RECIPROCITY_UNKNOWN',
			description:
				'Reciprocity is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'RECIPROCAL', description: 'Reciprocal' },
		{ label: 'NON_RECIPROCAL', description: 'Non-reciprocal' },
	],
	tense: [
		{
			label: 'TENSE_UNKNOWN',
			description:
				'Tense is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'CONDITIONAL_TENSE', description: 'Conditional' },
		{ label: 'FUTURE', description: 'Future' },
		{ label: 'PAST', description: 'Past' },
		{ label: 'PRESENT', description: 'Present' },
		{ label: 'IMPERFECT', description: 'Imperfect' },
		{ label: 'PLUPERFECT', description: 'Pluperfect' },
	],
	voice: [
		{
			label: 'VOICE_UNKNOWN',
			description:
				'Voice is not applicable in the analyzed language or is not predicted.',
		},
		{ label: 'ACTIVE', description: 'Active' },
		{ label: 'CAUSATIVE', description: 'Causative' },
		{ label: 'PASSIVE', description: 'Passive' },
	],
	label: [
		{ label: 'UNKNOWN', description: 'Unknown' },
		{ label: 'ABBREV', description: 'Abbreviation modifier' },
		{ label: 'ACOMP', description: 'Adjectival complement' },
		{ label: 'ADVCL', description: 'Adverbial clause modifier' },
		{ label: 'ADVMOD', description: 'Adverbial modifier' },
		{ label: 'AMOD', description: 'Adjectival modifier of an NP' },
		{ label: 'APPOS', description: 'Appositional modifier of an NP' },
		{ label: 'ATTR', description: 'Attribute dependent of a copular verb' },
		{ label: 'AUX', description: 'Auxiliary verb' },
		{ label: 'AUXPASS', description: 'Passive auxiliary' },
		{ label: 'CC', description: 'Coordinating conjunction' },
		{ label: 'CCOMP', description: 'Clausal complement of a verb or adjective' },
		{ label: 'CONJ', description: 'Conjunct' },
		{ label: 'CSUBJ', description: 'Clausal subject' },
		{ label: 'CSUBJPASS', description: 'Clausal passive subject' },
		{ label: 'DEP', description: 'Dependency (unable to determine)' },
		{ label: 'DET', description: 'Determiner' },
		{ label: 'DISCOURSE', description: 'Discourse' },
		{ label: 'DOBJ', description: 'Direct object' },
		{ label: 'EXPL', description: 'Expletive' },
		{
			label: 'GOESWITH',
			description: 'Goes with (part of a word in a text not well edited)',
		},
		{ label: 'IOBJ', description: 'Indirect object' },
		{ label: 'MARK', description: 'Marker (word introducing a subordinate clause)' },
		{ label: 'MWE', description: 'Multi-word expression' },
		{ label: 'MWV', description: 'Multi-word verbal expression' },
		{ label: 'NEG', description: 'Negation modifier' },
		{ label: 'NN', description: 'Noun compound modifier' },
		{ label: 'NPADVMOD', description: 'Noun phrase used as an adverbial modifier' },
		{ label: 'NSUBJ', description: 'Nominal subject' },
		{ label: 'NSUBJPASS', description: 'Passive nominal subject' },
		{ label: 'NUM', description: 'Numeric modifier of a noun' },
		{ label: 'NUMBER', description: 'Element of compound number' },
		{ label: 'P', description: 'Punctuation mark' },
		{ label: 'PARATAXIS', description: 'Parataxis relation' },
		{ label: 'PARTMOD', description: 'Participial modifier' },
		{ label: 'PCOMP', description: 'The complement of a preposition is a clause' },
		{ label: 'POBJ', description: 'Object of a preposition' },
		{ label: 'POSS', description: 'Possession modifier' },
		{ label: 'POSTNEG', description: 'Postverbal negative particle' },
		{ label: 'PRECOMP', description: 'Predicate complement' },
		{ label: 'PRECONJ', description: 'Preconjunt' },
		{ label: 'PREDET', description: 'Predeterminer' },
		{ label: 'PREF', description: 'Prefix' },
		{ label: 'PREP', description: 'Prepositional modifier' },
		{
			label: 'PRONL',
			description: 'The relationship between a verb and verbal morpheme',
		},
		{ label: 'PRT', description: 'Particle' },
		{ label: 'PS', description: 'Associative or possessive marker' },
		{ label: 'QUANTMOD', description: 'Quantifier phrase modifier' },
		{ label: 'RCMOD', description: 'Relative clause modifier' },
		{ label: 'RCMODREL', description: 'Complementizer in relative clause' },
		{ label: 'RDROP', description: 'Ellipsis without a preceding predicate' },
		{ label: 'REF', description: 'Referent' },
		{ label: 'REMNANT', description: 'Remnant' },
		{ label: 'REPARANDUM', description: 'Reparandum' },
		{ label: 'ROOT', description: 'Root' },
		{ label: 'SNUM', description: 'Suffix specifying a unit of number' },
		{ label: 'SUFF', description: 'Suffix' },
		{ label: 'TMOD', description: 'Temporal modifier' },
		{ label: 'TOPIC', description: 'Topic marker' },
		{
			label: 'VMOD',
			description:
				'Clause headed by an infinite form of the verb that modifies a noun',
		},
		{ label: 'VOCATIVE', description: 'Vocative' },
		{ label: 'XCOMP', description: 'Open clausal complement' },
		{ label: 'SUFFIX', description: 'Name suffix' },
		{ label: 'TITLE', description: 'Name title' },
		{ label: 'ADVPHMOD', description: 'Adverbial phrase modifier' },
		{ label: 'AUXCAUS', description: 'Causative auxiliary' },
		{ label: 'AUXVV', description: 'Helper auxiliary' },
		{ label: 'DTMOD', description: 'Rentaishi (Prenominal modifier)' },
		{ label: 'FOREIGN', description: 'Foreign words' },
		{ label: 'KW', description: 'Keyword' },
		{ label: 'LIST', description: 'List for chains of comparable items' },
		{ label: 'NOMC', description: 'Nominalized clause' },
		{ label: 'NOMCSUBJ', description: 'Nominalized clausal subject' },
		{ label: 'NOMCSUBJPASS', description: 'Nominalized clausal passive' },
		{ label: 'NUMC', description: 'Compound of numeric modifier' },
		{ label: 'COP', description: 'Copula' },
		{
			label: 'DISLOCATED',
			description: 'Dislocated relation (for fronted/topicalized elements)',
		},
		{ label: 'ASP', description: 'Aspect marker' },
		{ label: 'GMOD', description: 'Genitive modifier' },
		{ label: 'GOBJ', description: 'Genitive object' },
		{ label: 'INFMOD', description: 'Infinitival modifier' },
		{ label: 'MES', description: 'Measure' },
		{ label: 'NCOMP', description: 'Nominal complement of a noun' },
	],
}

export default googleTags
