# Generated by Django 4.1.5 on 2023-05-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('lexicon', models.JSONField(blank=True, default=dict, null=True)),
                ('notes', models.JSONField(blank=True, default=dict, null=True)),
                ('level', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapter', models.SmallIntegerField()),
                ('text', models.CharField(max_length=3000)),
                ('textData', models.JSONField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.book')),
            ],
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('book', 'chapter'), name='uniqueBookChapter'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('book', 'title'), name='uniqueTextTitle'),
        ),
    ]
