# Generated by Django 4.1.5 on 2023-05-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lexicon',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
